"""
Модуль моделей данных.

Объединяет и экспортирует все модели SQLAlchemy, Pydantic и перечисления (enums)
для удобного доступа из других частей приложения.
"""

from .enums import (
    EndConditionType,
    IntervalUnit,
    LenderType,
    LoanStatus,
    LoanType,
    OccurrenceStatus,
    PaymentStatus,
    PendingPaymentPriority,
    PendingPaymentStatus,
    RecurrenceType,
    TransactionType,
)
from .models import (
    Base,
    Category,
    CategoryCreate,
    CategoryDB,
    Lender,
    LenderCreate,
    LenderDB,
    LenderUpdate,
    Loan,
    LoanCreate,
    LoanDB,
    LoanPayment,
    LoanPaymentCreate,
    LoanPaymentDB,
    LoanUpdate,
    PendingPayment,
    PendingPaymentCancel,
    PendingPaymentCreate,
    PendingPaymentDB,
    PendingPaymentExecute,
    PendingPaymentUpdate,
    PlannedOccurrence,
    PlannedOccurrenceCreate,
    PlannedOccurrenceDB,
    PlannedTransaction,
    PlannedTransactionCreate,
    PlannedTransactionDB,
    RecurrenceRule,
    RecurrenceRuleCreate,
    RecurrenceRuleDB,
    Transaction,
    TransactionCreate,
    TransactionDB,
    TransactionUpdate,
)

__all__ = [
    # Enums
    "TransactionType",
    "RecurrenceType",
    "OccurrenceStatus",
    "IntervalUnit",
    "EndConditionType",
    "LenderType",
    "LoanType",
    "LoanStatus",
    "PaymentStatus",
    "PendingPaymentPriority",
    "PendingPaymentStatus",
    # SQLAlchemy DB Models
    "Base",
    "CategoryDB",
    "PlannedTransactionDB",
    "RecurrenceRuleDB",
    "PlannedOccurrenceDB",
    "TransactionDB",
    "LenderDB",
    "LoanDB",
    "LoanPaymentDB",
    "PendingPaymentDB",
    # Pydantic Models
    "TransactionCreate",
    "TransactionUpdate",
    "Transaction",
    "Category",
    "CategoryCreate",
    "PlannedTransactionCreate",
    "PlannedTransaction",
    "RecurrenceRuleCreate",
    "RecurrenceRule",
    "PlannedOccurrenceCreate",
    "PlannedOccurrence",
    "Lender",
    "LenderCreate",
    "LenderUpdate",
    "Loan",
    "LoanCreate",
    "LoanUpdate",
    "LoanPaymentCreate",
    "LoanPayment",
    "PendingPaymentCreate",
    "PendingPaymentUpdate",
    "PendingPaymentExecute",
    "PendingPaymentCancel",
    "PendingPayment",
]